-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg6Iqk3J4FWZpidRII
U7nZfknqKtOoi1fmkGYyE5ecpL6gCgYIKoZIzj0DAQehRANCAATLvMBrInIutNXu
jHrQ1GXd5Km8hE+3DIMl53GCiTeFV8UrJWnC9kmAgvjWL63iIowCj7TFbtBgCySs
b/Li2yBi
-----END PRIVATE KEY-----